### ISSUE TITLE
[Feature] Customizable expiration times

### ISSUE THREAD

**Issue by Jack-Edwards** [Crypter-File-Transfer/Crypter#194]
**Describe the feature**

Crypter automatically expires (and deletes) all items after 24 hours.  However, users may want to define their own expiration times.

Give users the ability to define when their uploads should expire.  24 hours can remain as the default expiration and the maximum expiration.

I personally do not care whether we allow users to set the expiration time down to the millisecond - the UI just needs to be clean and easy to use.

**Implementation Notes**

I would begin by modifying the Crypter.Contracts -> `ITransferRequest` interface.  Add a `RequestedExpiration` property to indicate when the user would *like* the transfer to be expired.  The API will need to verify the requested expiration is valid.

After that, add UI to Crypter.Web that allows users to define a custom expiration time.

Finally, Crypter.API needs to handle the new property.  The value should be validated and used in-place of the default 24 hours.

**Bonus**
Currently, Crypter.Console is run every 5 minutes using `cron`.  This is how we periodically delete expired items.

I would like to stop using `cron` and Crypter.Console for this.  I think Hangfire is a better option.

**Comment by jakubstankowski** [comment]
Great idea,
I have a few questions:
1.  how user can set the expieration? By simple number input where it will be validation between 1-24 hours, or maybe select with some values (like 1 hour, 2, 6, 12, 24), or maybe the same options but with buttons?
2. The RequestedExpiration should be a number, or a date? Maybe simple int type and validation there, then i'll create date inside the API depends of value

**Comment by Jack-Edwards** [comment]
The API should accept the requested expiration as a UTC DateTime field.  That should make things more flexible for the client.  The API should verify the requested DateTime is not more than 24 hours in the future.

I think a simple number input field on the front-end should be fine.  Minimum = 1, Maximum = 24.
