### ISSUE TITLE
[Bug] Uploads may fail with valid, requested expiration times

### ISSUE THREAD

**Issue by Jack-Edwards** [Crypter-File-Transfer/Crypter#219]
**Describe the bug**

Some of my uploads have failed since #194 was merged.  The API was rejecting requests when I set RequestedExpirationHours to 1.

While trying to fix the issue, I realized we did not consider the situation where the client's clock could be ahead or behind the server's clock.  This can also lead to failed uploads.

Consider this scenario:

1. Server time is 12:00.
2. Client time is 12:05.
3. Client requests an expiration time of 24 hours (12:05 the next day).
4. The server evaluates the request and rejects it, because 12:05 on the next day is greater than 24 hours ahead of the server.

Possible solutions:

1. Add some buffer to the server's evaluation.  `.AddHours(1).SubtractMinutes(5)` and `.AddHours(24).AddMinutes(5)` for example.
2. Modify the `ITransferRequest` contract to accept a number of hours for expiration, rather than a `DateTime`.

**Comment by Jack-Edwards** [comment]
@jakubstankowski Let me know what you think.  There may be other solutions to this problem.  Although solution 1 is more flexible (the client can request any arbitrary DateTime as the expiration time), solution 2 will always succeed.

I think I prefer solution 2.

**Comment by Jack-Edwards** [comment]
@jakubstankowski I implemented a solution this evening.

**Comment by jakubstankowski** [comment]
yes it's very important to fis this bug, and i think your solution @Jack-Edwards is really good
