### ISSUE TITLE
[Feature] Default "Remember me" to true

### ISSUE THREAD

**Issue by Jack-Edwards** [Crypter-File-Transfer/Crypter#256]
**Describe the feature**
Modify the login component so the "Remember me" option defaults to true.

For reference:
https://github.com/Crypter-File-Transfer/Crypter/blob/main/Crypter.Web/Shared/LoginComponent.razor.cs

**Comment by ez-sherlock** [comment]
Please assign this to me. Thanks :)

**Comment by Jack-Edwards** [comment]
@ez-sherlock Done.  Thanks for offering to take this on.  I updated the issue description with a link to the component.

**Comment by ez-sherlock** [comment]
Can I get the issue's website link too?

**Comment by Jack-Edwards** [comment]
Could you elaborate?  I don't think I understand which link you are asking for.

**Comment by ez-sherlock** [comment]
I made the pull request. Please have a look at it. Thanks 💯

**Comment by ez-sherlock** [comment]
@Jack-Edwards So sorry I just read the contribution guidelines. Should I delete this pull request and create a new one with the changes or is it fine by you?

**Comment by Jack-Edwards** [comment]
Definitely don't merge this directly to the main branch. Modify this PR or submit a new one so the target branch is "dev".

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ez-sherlock** [comment]
I again made a pull request. Have a look at it.
