### ISSUE TITLE
[Bug] Typo on About page

### ISSUE THREAD

**Issue by Jack-Edwards** [Crypter-File-Transfer/Crypter#352]
There exists a typographical error on the website's "About" page.

https://github.com/Crypter-File-Transfer/Crypter/blob/main/Crypter.Web/Pages/About.razor

This text:
> I had an Android phone so we I could not AirDrop it to her iPhone.

Should read:
> I had an Android phone so I could not AirDrop the file to her iPhone.

**Comment by Shawncologist** [comment]
Corrected this typo in pull request 357 (I am not confident the pull request was done correctly by me though).

**Comment by Jack-Edwards** [comment]
Pull request #357 refers to something different.  In your situation, the correct procedure for submitting a pull request would be to:
1. Make a fork of this repository under your account.
2. Create a new branch for your fix. Branch off the `dev` branch.
3. Commit the fix to this branch.
4. Push the fix to your repository.
5. There should be an option on your repository to create a pull request from your repo to this one.
