### ISSUE TITLE
Remove `_modalClassShow` from `ModalBehavior` front-end component

### ISSUE THREAD

**Issue by Jack-Edwards** [Crypter-File-Transfer/Crypter#508]
## Description

There is a variable in the `ModalBehavior.razor.z` code called `_modalClassShow`.  This variable has been around for years, but it doesn't appear to actually do or affect anything.

Verify the variable is unnecessary and remove it.

## Good First Issue

This is a good first issue for anyone interested in front-end development using ASP.NET and Blazor.

**Comment by Exilon24** [comment]
I've removed **_modalClassShow** and I ran some of the unit tests and it doesn't seem to affect anything. It doesn't seem to be used anywhere either. The only problem is, I don't know how actually test the app to see if it works without that variable (I'm still new to this stuff 😅). Any advice?

**Comment by Jack-Edwards** [comment]
Currently, none of the unit tests in the repo will verify the look or behavior of UI components.  But the front-end should be building successfully if you are able to run unit tests, so that is a good step.

Have you gone through this document on how to setup a local development environment?  [Development Environment Setup](https://github.com/Crypter-File-Transfer/Crypter/blob/main/Documentation/Development/Development%20Environment%20Setup.md)

For this issue specifically, it's sufficient to verify modal windows open/close and the background fades/un-fades on the front-end.  Every modal inherits from the class you are modifying, so it should be fine to test just one or two modals.  User registration and login should prompt a few modals to appear.

**Comment by Jack-Edwards** [comment]
@Exilon24 If you want to give this another try, I suggest pulling the latest code from `main` or `stable` branch.  Run `docker-compose --profile dev up` in the solution directory.  The whole project should "just work" when you navigate to `https://localhost`.
