### ISSUE TITLE
[Bug] Transfer notifications are queued regardless of user settings

### ISSUE THREAD

**Issue by Jack-Edwards** [Crypter-File-Transfer/Crypter#547]
**Describe the bug**

This method in the Crypter.Core => TransferUploadService.cs is faulty.  The background job should not be enqueued unless a matching user is found.

```
private async Task<Unit> QueueTransferNotificationAsync(Guid itemId, TransferItemType itemType, Maybe<Guid> maybeUserId)
      {
         await maybeUserId.IfSomeAsync(
            async userId =>
            {
               UserEntity user = await _context.Users
                  .Where(x => x.Id == userId)
                  .Where(x => x.NotificationSetting.EnableTransferNotifications
                     && x.EmailVerified
                     && x.NotificationSetting.EmailNotifications)
                  .FirstOrDefaultAsync();

               _backgroundJobClient.Enqueue(() => _hangfireBackgroundService.SendTransferNotificationAsync(itemId, itemType));
            });
         return Unit.Default;
      }
```

This is a good first issue for anyone wanting to contribute to an ASP.NET project.  `_backgroundJobClient.Enqueue(() => ...);` literally just needs to be wrapped in an `if` condition.  Do not enqueue if the `user` is null.

May also be better to query for AnyAsync rather than FirstOrDefaultAsync.  The queued method doesn't appear to need any user information.

**Comment by tacosontitan** [comment]
I'll take it on!
