### ISSUE TITLE
[Feature] Use 'AddDbContextPool' instead of 'AddDbContext'

### ISSUE THREAD

**Issue by Jack-Edwards** [Crypter-File-Transfer/Crypter#564]
## Description

It would be a good idea to take advantage of Entity Framework Core's context pooling feature.  This should result overall better performance when handling multiple requests in a short time frame.

The DbContext is currently added to the API via `Crypter.Core` => `DependencyInjection.cs` => `AddCrypterCore()`.  Just swap out `AddDbContext` for `AddDbContextPool`.  If unit tests are still passing then everything should be fine.

## Good First Issue

This is a good first issue for anyone interested in ASP.NET and Entity Framework Core.

**Comment by rkj43** [comment]
Hello,
I would like to try this issue!
Could you please assign it to me?

**Comment by Jack-Edwards** [comment]
Of course!  Let me know if you have any questions or run into problems.

It's not documented anywhere yet, but you'll need to have Docker running in order to run any unit tests.

**Comment by Jack-Edwards** [comment]
Interesting. Try `--profile dev` instead.
-------- Original Message --------

**Comment by Jack-Edwards** [comment]
That's a really odd error to receive during build.  Building should not require any services to be running.  I don't want to get too deep into debugging a Docker problem, but what OS and version of Docker are you using?

**Comment by rkj43** [comment]
Docker version 24.0.2, build cb74dfc
Windows 10

**Comment by rkj43** [comment]
`docker-compose --profile dev` build is working but when I do `docker-compose --profile dev up`
I get the following error :
`crypter-db-1   | 2023-07-06 15:29:02.735 UTC [40] FATAL:  database "crypter" does not exist
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/d/Opensourse/Crypter/Containers/API/appsettings.json" to rootfs at "/app/appsettings.json": mount /run/desktop/mnt/host/d/Opensourse/Crypter/Containers/API/appsettings.json:/app/appsettings.json (via /proc/self/fd/9), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

**Comment by Jack-Edwards** [comment]
Yeah that's an error on my part.  The line endings in /Volumes/PostgreSQL/postgres-init-files/init.sh are Windows line endings.  They need to be Unix line endings.  I just discovered this myself.

I will get an update to the Stable branch that fixes this.

**Comment by Jack-Edwards** [comment]
It appears the version of the file in the `stable` branch already has Unix line endings.  The file may have converted to Windows line endings on your end - which is probably what also happened to me.

Make you you checkout files "as-is" and are not converting any line endings when you pull.

**Comment by rkj43** [comment]
Ahh, Alright.
Its working now.
I made the change from AddDbContext  to AddDbContextPool
90+ unit tests are failing because of these two errors:
`System.InvalidOperationException : The DbContext of type 'DataContext' cannot be pooled because it does not have a public constructor accepting a single parameter of type DbContextOptions or has more than one constructor.`
`System.InvalidOperationException : 'OnConfiguring' cannot be used to modify DbContextOptions when DbContext pooling is enabled.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.`

I'm thinking I would need to change up the constructor in DataContext to something like this :
` public DataContext(DbContextOptions<DataContext> options) : base(options)
      {
      }`
      
     and would also have to remove the OnConfiguring method.
     
     I have actually implemented the changes mentioned above and its working with all the unit tests passing, but should I do something about the logging thats been removed as a result of these changes?

**Comment by Jack-Edwards** [comment]
I would really prefer to keep the logging functionality.

What may work just as well is moving the logging functionality to the `AddDbContextPool` setup.  Something like this:

```
services.AddDbContextPool<DataContext>(optionsBuilder =>
{
    optionsBuilder.UseNpgSql(...);
    optionsBuilder.LogTo(...);
}
```

You would just need to resolve an instance of the ILogger somewhere during startup.
